version: "3.1"

services:

  postgres-db:
    
    image: postgres

    restart: always

    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test-db
      
      
  server:  

    build: ./server/

    restart: always

    environment:
      - USER_NAME=user
      - PASSWORD=password
      - DB_HOST=postgres-db
      - DB=test-db
      - PORT=80

    ports:
      - 8080:80

    depends_on:
      - postgres-db


  clients:

    build: ./clients/

    restart: always

    depends_on:
      - server

    ports:
      - 4200:4200

